name: "safeguard-io"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
          - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
          - database_data:/var/lib/postgresql/data

    #react-chatbot:
    #    depends_on:
     #       postgres:
      #          condition: service_healthy
       # build:
        #    context: ./src
    #        dockerfile: Dockerfile
     #   env_file:
      #    - .env
       # volumes:
        #  - ./src:/app

volumes:
    database_data:
        driver: local