# Dockerfile.verif_process
FROM python:3.10.14-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app

ENV PYTHONPATH=/app

CMD ["python3", "verif_process/verif_processing.py"]